/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class Constants {
  // icon of dialog
  static DIALOG_ICON_WIDTH = 24;
  static DIALOG_ICON_HEIGHT = 24;
  static DIALOG_ICON_MARGIN_TOP = 24;

  // label text of dialog
  static DIALOG_LABEL_FONT_SIZE = 14;
  static DIALOG_LABEL_MARGIN_TOP = 2;

  // request text of dialog
  static DIALOG_REQ_FONT_SIZE = 16;
  static DIALOG_REQ_MARGIN_TOP = 16;
  static DIALOG_REQ_MARGIN_LEFT = 24;

  // description text of dialog
  static DIALOG_DESP_FONT_SIZE = 14;
  static DIALOG_DESP_MARGIN_TOP = 2;
  static DIALOG_DESP_MARGIN_LEFT = 24;

  static BUTTON_FONT_SIZE = 16;
  static BUTTON_DIVIDER_FONT_SIZE = 30;
  static BUTTON_MARGIN_TOP = 8;

  static DIALOG_BORDER_RADIUS = 24;
  static DIALOG_HEIGHT = 186;
  static DIALOG_WIDTH = "100%";

  // initial check status
  static INIT_NEED_TO_WAIT = 0
  static INIT_NEED_TO_VERIFY = 1
  static INIT_NEED_TO_TERMINATED = 2

  static RESULT_SUCCESS = 1
  static RESULT_FAILURE = 0
}