/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const calendarListItem: any[] = [
  { 'name': '读取日历', 'index': 1 },
  { 'name': '新建/修改/删除日历', 'index': 2 }
]
export const dynamicListItem: any[] = [
  { 'name': 'xxxxxx', 'index': 1 },
  { 'name': 'xxxxxx', 'index': 2 }
]
export const allowedListItem: any[] = [
  { 'name': '相机', 'index': 1, permission:'' },
  { 'name': '麦克风', 'index': 2, permission:'' },
  { 'name': '媒体和文件', 'index': 3, permission:'仅媒体' },
  { 'name': '日历', 'index': 4, permission:'读取日历' }
]
export const bannedListItem: any[] = [
  { 'name': '悬浮窗', 'index': 1 }
]