/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const authorityListItem: any[] = [
  { 'name': '位置信息', 'index': 1, 'image': $r('app.media.ic_public_gps'), 'icon': $r('app.media.rightarrow'), version: '1.1.1', use: '用途001' },
  { 'name': '相机', 'index': 2, 'image': $r('app.media.ic_public_camera'), 'icon': $r('app.media.rightarrow'), version: '1.1.1', use: '用途001' },
  { 'name': '麦克风', 'index': 3, 'image': $r('app.media.ic_public_voice'), 'icon': $r('app.media.rightarrow'), version: '1.1.1', use: '用途001' },
]
export const messageListItem: any[] = [
  { 'name': '媒体和文件', 'index': 1, 'image': $r('app.media.ic_public_folder'), 'icon': $r('app.media.rightarrow'), version: '1.1.1', use: '用途001' },
  { 'name': '日历', 'index': 2, 'image': $r('app.media.ic_public_calendar'), 'icon': $r('app.media.rightarrow'), version: '1.1.1', use: '用途001' },
  { 'name': '健身运动', 'index': 3, 'image': $r('app.media.ic_sport'), 'icon': $r('app.media.rightarrow'), version: '1.1.1', use: '用途001' },
  { 'name': '身体传感器', 'index': 4, 'image': $r('app.media.ic_ssensor'), 'icon': $r('app.media.rightarrow'), version: '1.1.1', use: '用途001' },
  { 'name': '多设备协同', 'index': 5, 'image': $r('app.media.ic_dropzone'), 'icon': $r('app.media.rightarrow'), version: '1.1.1', use: '用途001' }
]
export const applicationListItem: any[] = [
  { 'name': '备忘录', 'index': 1, 'image': $r('app.media.beiwanglu'), 'message': '6项权限', 'icon': $r('app.media.rightarrow'), alphabeticalIndex: 'B' },
  { 'name': '拨号权限', 'index': 2, 'image': $r('app.media.phone'), 'message': '5项权限', 'icon': $r('app.media.rightarrow'), alphabeticalIndex: 'B' },
  { 'name': '电子邮件', 'index': 3, 'image': $r('app.media.baiduwangpan'), 'message': '1项权限', 'icon': $r('app.media.rightarrow'), alphabeticalIndex: 'D' },
  { 'name': '华为视频', 'index': 4,'image': $r('app.media.bilibili'), 'message': '5项权限', 'icon': $r('app.media.rightarrow'), alphabeticalIndex: 'H' },
  { 'name': '联系人', 'index': 5, 'image': $r('app.media.tongxunlu'), 'message': '5项权限', 'icon': $r('app.media.rightarrow'), alphabeticalIndex: 'L' },
  { 'name': '日历', 'index': 6, 'image': $r('app.media.ic_public_calendar'), 'message': '5项权限', 'icon': $r('app.media.rightarrow'), alphabeticalIndex: 'R' },
  { 'name': '手机管家', 'index': 7, 'image': $r('app.media.weixin'), 'message': '5项权限', 'icon': $r('app.media.rightarrow'), alphabeticalIndex: 'S' },
  { 'name': '图库', 'index': 8, 'image': $r("app.media.photo"), 'message': '5项权限', 'icon': $r('app.media.rightarrow'), alphabeticalIndex: 'T' }
]
