/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const categoryListItem: any[] = [
  { 'name': '声音和振动', 'index': 1, 'image': $r('app.media.shengyin'), 'icon': $r('app.media.rightarrow') },
  { 'name': '通知', 'index': 2, 'image': $r('app.media.tongzhi'), 'icon': $r('app.media.rightarrow') },
  { 'name': '生物识别', 'index': 3, 'image': $r('app.media.shibie'), 'icon': $r('app.media.rightarrow') },
  { 'name': '应用和服务', 'index': 4,'image': $r('app.media.yingyong'), 'icon': $r('app.media.rightarrow') },
  { 'name': '电池', 'index': 5, 'image': $r('app.media.dianchi'), 'icon': $r('app.media.rightarrow') },
  { 'name': '存储', 'index': 6, 'image': $r('app.media.cunchu'), 'icon': $r('app.media.rightarrow') },
  { 'name': '安全', 'index': 7, 'image': $r('app.media.anquan'), 'icon': $r('app.media.rightarrow') },
  { 'name': '隐私', 'index': 8, 'image': $r('app.media.yinsi'), 'icon': $r('app.media.rightarrow') },
  { 'name': '平板健康', 'index': 9, 'image': $r('app.media.jiankang'), 'icon': $r('app.media.rightarrow') },
  { 'name': '应用设置', 'index': 10, 'image': $r('app.media.shezhi'), 'icon': $r('app.media.rightarrow') }
]