/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const definePermissions: any[] = [
  {
    "name": "ohos.permission.ANSWER_CALL",
    "grantMode": "user_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_answer_call",
    "description": "$string:ohos_desc_answer_call"
  },
  {
    "name": "ohos.permission.USE_BLUETOOTH",
    "grantMode": "system_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.DISCOVER_BLUETOOTH",
    "grantMode": "system_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.MANAGE_BLUETOOTH",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.INTERNET",
    "grantMode": "system_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_internet",
    "description": "$string:ohos_desc_internet"
  },
  {
    "name": "ohos.permission.MODIFY_AUDIO_SETTINGS",
    "grantMode": "system_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_modify_audio_settings",
    "description": "$string:ohos_desc_modify_audio_settings"
  },
  {
    "name": "ohos.permission.READ_CALENDAR",
    "grantMode": "user_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_read_calendar",
    "description": "$string:ohos_desc_read_calendar"
  },
  {
    "name": "ohos.permission.READ_CALL_LOG",
    "grantMode": "user_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_read_call_log",
    "description": "$string:ohos_desc_read_call_log"
  },
  {
    "name": "ohos.permission.READ_CELL_MESSAGES",
    "grantMode": "user_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_read_cell_messages",
    "description": "$string:ohos_desc_read_cell_messages"
  },
  {
    "name": "ohos.permission.READ_CONTACTS",
    "grantMode": "user_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_read_contacts",
    "description": "$string:ohos_desc_read_contacts"
  },
  {
    "name": "ohos.permission.GET_TELEPHONY_STATE",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_get_telephony_state",
    "description": "$string:ohos_desc_get_telephony_state"
  },
  {
    "name": "ohos.permission.READ_MESSAGES",
    "grantMode": "user_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_read_messages",
    "description": "$string:ohos_desc_read_messages"
  },
  {
    "name": "ohos.permission.RECEIVE_MMS",
    "grantMode": "user_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_receive_mms",
    "description": "$string:ohos_desc_receive_mms"
  },
  {
    "name": "ohos.permission.RECEIVE_SMS",
    "grantMode": "user_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_receive_sms",
    "description": "$string:ohos_desc_receive_sms"
  },
  {
    "name": "ohos.permission.RECEIVE_WAP_MESSAGES",
    "grantMode": "user_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_receive_wap_messages",
    "description": "$string:ohos_desc_receive_wap_messages"
  },
  {
    "name": "ohos.permission.MICROPHONE",
    "grantMode": "user_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_microphone",
    "description": "$string:ohos_desc_microphone"
  },
  {
    "name": "ohos.permission.SEND_MESSAGES",
    "grantMode": "user_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_send_messages",
    "description": "$string:ohos_desc_send_messages"
  },
  {
    "name": "ohos.permission.WRITE_CALENDAR",
    "grantMode": "user_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_write_calendar",
    "description": "$string:ohos_desc_write_calendar"
  },
  {
    "name": "ohos.permission.WRITE_CALL_LOG",
    "grantMode": "user_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_write_call_log",
    "description": "$string:ohos_desc_write_call_log"
  },
  {
    "name": "ohos.permission.WRITE_CONTACTS",
    "grantMode": "user_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_write_contacts",
    "description": "$string:ohos_desc_write_contacts"
  },
  {
    "name": "ohos.permission.DISTRIBUTED_DATASYNC",
    "grantMode": "user_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": true,
    "label": "$string:ohos_lab_distributed_datasync",
    "description": "$string:ohos_desc_distributed_datasync"
  },
  {
    "name": "ohos.permission.MANAGE_VOICEMAIL",
    "grantMode": "user_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_manage_voicemail",
    "description": "$string:ohos_desc_manage_voicemail"
  },
  {
    "name": "ohos.permission.REQUIRE_FORM",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.LOCATION_IN_BACKGROUND",
    "grantMode": "user_grant",
    "availableScope": "normal",
    "provisionEnable": false,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_location_in_background",
    "description": "$string:ohos_desc_location_in_background"
  },
  {
    "name": "ohos.permission.LOCATION",
    "grantMode": "user_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": true,
    "label": "$string:ohos_lab_location",
    "description": "$string:ohos_desc_location"
  },
  {
    "name": "ohos.permission.MEDIA_LOCATION",
    "grantMode": "user_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": true,
    "label": "$string:ohos_lab_media_location",
    "description": "$string:ohos_desc_media_location"
  },
  {
    "name": "ohos.permission.GET_NETWORK_INFO",
    "grantMode": "system_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_get_network_info",
    "description": "$string:ohos_desc_get_network_info"
  },
  {
    "name": "ohos.permission.PLACE_CALL",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": true,
    "label": "$string:ohos_lab_place_call",
    "description": "$string:ohos_desc_place_call"
  },
  {
    "name": "ohos.permission.CAMERA",
    "grantMode": "user_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_camera",
    "description": "$string:ohos_desc_camera"
  },
  {
    "name": "ohos.permission.SET_NETWORK_INFO",
    "grantMode": "system_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_set_network_info",
    "description": "$string:ohos_desc_set_network_info"
  },
  {
    "name": "ohos.permission.REMOVE_CACHE_FILES",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.READ_MEDIA",
    "grantMode": "user_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": true,
    "label": "$string:ohos_lab_read_media",
    "description": "$string:ohos_desc_read_media"
  },
  {
    "name": "ohos.permission.REBOOT",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.RUNNING_LOCK",
    "grantMode": "system_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.WRITE_MEDIA",
    "grantMode": "user_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": true,
    "label": "$string:ohos_lab_write_media",
    "description": "$string:ohos_desc_write_media"
  },
  {
    "name": "com.huawei.permission.DISTRIBUTED_VIRTUALDEVICE",
    "grantMode": "user_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_distributed_virtualdevice",
    "description": "$string:ohos_desc_distributed_virtualdevice"
  },
  {
    "name": "ohos.permission.ENROLL_BIOMETRIC",
    "grantMode": "system_grant",
    "availableScope": "system_core",
    "provisionEnable": false,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_enroll_biometric",
    "description": "$string:ohos_desc_enroll_biometric"
  },
  {
    "name": "ohos.permission.ACCESS_BIOMETRIC",
    "grantMode": "system_grant",
    "availableScope": "normal",
    "provisionEnable": false,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_access_biometric",
    "description": "$string:ohos_desc_access_biometric"
  },
  {
    "name": "ohos.permission.ACCESS_BIOMETRIC_INTERNAL",
    "grantMode": "system_grant",
    "availableScope": "system_core",
    "provisionEnable": false,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_access_biometric_internal",
    "description": "$string:ohos_desc_access_biometric_internal"
  },
  {
    "name": "ohos.permission.RESET_BIOMETRIC_LOCKOUT",
    "grantMode": "system_grant",
    "availableScope": "system_core",
    "provisionEnable": false,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_reset_biometric_lockout",
    "description": "$string:ohos_desc_reset_biometric_lockout"
  },
  {
    "name": "ohos.permission.SET_TIME",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_set_time",
    "description": "$string:ohos_desc_set_time"
  },
  {
    "name": "ohos.permission.SET_TIME_ZONE",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_set_time_zone",
    "description": "$string:ohos_desc_set_time_zone"
  },
  {
    "name": "ohos.permission.DOWNLOAD_SESSION_MANAGER",
    "grantMode": "system_grant",
    "availableScope": "system_core",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_download_session_manager",
    "description": "$string:ohos_desc_download_session_manager"
  },
  {
    "name": "ohos.permission.COMMONEVENT_STICKY",
    "grantMode": "system_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": true,
    "label": "$string:ohos_lab_commonevent_sticky",
    "description": "$string:ohos_desc_commonevent_sticky"
  },
  {
    "name": "ohos.permission.SYSTEM_FLOAT_WINDOW",
    "grantMode": "system_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.POWER_MANAGER",
    "grantMode": "system_grant",
    "availableScope": "system_core",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.REFRESH_USER_ACTION",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.POWER_OPTIMIZATION",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.REBOOT_RECOVERY",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.MANAGE_LOCAL_ACCOUNTS",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_manage_local_accounts",
    "description": "$string:ohos_desc_manage_local_accounts"
  },
  {
    "name": "ohos.permission.INTERACT_ACROSS_LOCAL_ACCOUNTS",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_interact_across_local_accounts",
    "description": "$string:ohos_desc_interact_across_local_accounts"
  },
  {
    "name": "ohos.permission.VIBRATE",
    "grantMode": "system_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_vibrate",
    "description": "$string:ohos_desc_vibrate"
  },
  {
    "name": "ohos.permission.ACTIVITY_MOTION",
    "grantMode": "user_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_activity_motion",
    "description": "$string:ohos_desc_activity_motion"
  },
  {
    "name": "ohos.permission.READ_HEALTH_DATA",
    "grantMode": "user_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_read_health_data",
    "description": "$string:ohos_desc_read_health_data"
  },
  {
    "name": "ohos.permission.CONNECT_IME_ABILITY",
    "grantMode": "system_grant",
    "availableScope": "system_core",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_connect_ime_ability",
    "description": "$string:ohos_desc_connect_ime_ability"
  },
  {
    "name": "ohos.permission.CONNECT_SCREEN_SAVER_ABILITY",
    "grantMode": "system_grant",
    "availableScope": "system_core",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.READ_SCREEN_SAVER",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.WRITE_SCREEN_SAVER",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.SET_WALLPAPER",
    "grantMode": "system_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_set_wallpaper",
    "description": "$string:ohos_desc_set_wallpaper"
  },
  {
    "name": "ohos.permission.GET_WALLPAPER",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_get_wallpaper",
    "description": "$string:ohos_desc_get_wallpaper"
  },
  {
    "name": "ohos.permission.CHANGE_ABILITY_ENABLED_STATE",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.ACCESS_MISSIONS",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.CLEAN_BACKGROUND_PROCESSES",
    "grantMode": "system_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.KEEP_BACKGROUND_RUNNING",
    "grantMode": "system_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.UPDATE_CONFIGURATION",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.GRANT_SENSITIVE_PERMISSIONS",
    "grantMode": "system_grant",
    "availableScope": "system_core",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.REVOKE_SENSITIVE_PERMISSIONS",
    "grantMode": "system_grant",
    "availableScope": "system_core",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.GET_SENSITIVE_PERMISSIONS",
    "grantMode": "system_grant",
    "availableScope": "system_core",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.INTERACT_ACROSS_LOCAL_ACCOUNTS_EXTENSION",
    "grantMode": "system_grant",
    "availableScope": "system_core",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_interact_across_local_accounts_extension",
    "description": "$string:ohos_desc_interact_across_local_accounts_extension"
  },
  {
    "name": "ohos.permission.LISTEN_BUNDLE_CHANGE",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.GET_BUNDLE_INFO",
    "grantMode": "system_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.ACCELEROMETER",
    "grantMode": "system_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_accelerometer",
    "description": "$string:ohos_desc_accelerometer"
  },
  {
    "name": "ohos.permission.GYROSCOPE",
    "grantMode": "system_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_gyroscope",
    "description": "$string:ohos_desc_gyroscope"
  },
  {
    "name": "ohos.permission.GET_BUNDLE_INFO_PRIVILEGED",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.INSTALL_BUNDLE",
    "grantMode": "system_grant",
    "availableScope": "system_core",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.MANAGE_SHORTCUTS",
    "grantMode": "system_grant",
    "availableScope": "system_core",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.radio.ACCESS_FM_AM",
    "grantMode": "system_grant",
    "availableScope": "system_core",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.SET_TELEPHONY_STATE",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_set_telephony_state",
    "description": "$string:ohos_desc_set_telephony_state"
  },
  {
    "name": "ohos.permission.START_ABILIIES_FROM_BACKGROUND",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.BUNDLE_ACTIVE_INFO",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_bundle_active_info",
    "description": "$string:ohos_desc_bundle_active_info"
  },
  {
    "name": "ohos.permission.START_INVISIBLE_ABILITY",
    "grantMode": "system_grant",
    "availableScope": "system_core",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.sec.ACCESS_UDID",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.LAUNCH_DATA_PRIVACY_CENTER",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.MANAGE_MEDIA_RESOURCES",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.PUBLISH_AGENT_REMINDER",
    "grantMode": "system_grant",
    "availableScope": "normal",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_publish_agent_reminder",
    "description": "$string:ohos_desc_publish_agent_reminder"
  },
  {
    "name": "ohos.permission.CONTROL_TASK_SYNC_ANIMATOR",
    "grantMode": "system_grant",
    "availableScope": "system_core",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_control_task_sync_animator",
    "description": "$string:ohos_desc_control_task_sync_animator"
  },
  {
    "name": "ohos.permission.INPUT_MONITORING",
    "grantMode": "system_grant",
    "availableScope": "system_core",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.MANAGE_MISSIONS",
    "grantMode": "system_grant",
    "availableScope": "system_core",
    "provisionEnable": true,
    "distributedSceneEnable": false
  },
  {
    "name": "ohos.permission.NOTIFICATION_CONTROLLER",
    "grantMode": "system_grant",
    "availableScope": "system_core",
    "provisionEnable": true,
    "distributedSceneEnable": false,
    "label": "$string:ohos_lab_notification_controller",
    "description": "$string:ohos_desc_notification_controller"
  },
  {
    "name": "ohos.permission.CONNECTIVITY_INTERNAL",
    "grantMode": "system_grant",
    "availableScope": "system_basic",
    "provisionEnable": true,
    "distributedSceneEnable": false
  }
]