/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const permissionAccessRecordListItem: any[] = [
  { 'name1': '微信', 'index': 1, 'image1': $r('app.media.weixin'), 'image2': $r('app.media.phone'), 'name2': '电话', 'visits': 16, 'lastVisitTime': '12月29日 上午12：22' },
  { 'name1': 'QQ', 'index': 2, 'image1': $r('app.media.qq'), 'image2': $r('app.media.phone'), 'name2': '电话', 'visits': 10, 'lastVisitTime': '12月30日 上午13：54' }
]